# Generated by Django 3.1 on 2020-08-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('birthdate', models.DateField(db_column='data_nascimento', verbose_name='Data de Nascimento')),
                ('admission_date', models.DateField(db_column='data_admissao', verbose_name='Data de admissão')),
                ('job_role', models.CharField(db_index=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'naver',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='NaverProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
                ('created_by', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('naver', models.ForeignKey(db_column='naver_id', on_delete=django.db.models.deletion.PROTECT, to='core.naver', verbose_name='naver')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='core.projeto', verbose_name='projeto')),
                ('updated_by', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto x Naver',
                'verbose_name_plural': 'Projetos x Navers',
                'db_table': 'naver_projeto',
                'unique_together': {('projeto', 'naver')},
            },
        ),
        migrations.AddField(
            model_name='naver',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='navers', through='core.NaverProjeto', to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='naver',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='naver', to=settings.AUTH_USER_MODEL),
        ),
    ]
